version: "3"
services:
  housemate.identityapi:
    image: housemate.identityapi
    build:
      context: .
      dockerfile: Housemate.Backend/Housemate.IdentityApi/Dockerfile
    ports:
      - "8001:80"
        
  housemate.housingtasksapi:
    image: housemate.housingtasksapi
    build:
      context: .
      dockerfile: Housemate.Backend/Housemate.HousingTasksApi/Dockerfile
    ports:
      - "8002:80"

  housemate.wastesapi:
    image: housemate.wastesapi
    build:
      context: .
      dockerfile: Housemate.Backend/Housemate.WastesApi/Dockerfile
    ports:
      - "8003:80"

  housemate.weatherapi:
    image: housemate.weatherapi
    build:
      context: .
      dockerfile: Housemate.Backend/Housemate.WeatherApi/Dockerfile
    ports:
      - "8004:80"

  housemate.apigateway:
    image: housemate.apigateway
    build:
      context: .
      dockerfile: Housemate.ApiGateway/Dockerfile
    ports:
      - "8000:80"
