version: "3"
services:
  housemate.identityapi:
    container_name: housemate_identityapi
    image: housemate.identityapi
    build:
      context: .
      dockerfile: Housemate.Backend/Housemate.IdentityApi/Dockerfile
    ports:
      - "8001:80"
        
  housemate.housingtasksapi:
    container_name: housemate_housingtaskapi
    image: housemate.housingtasksapi
    build:
      context: .
      dockerfile: Housemate.Backend/Housemate.HousingTasksApi/Dockerfile
    ports:
      - "8002:80"

  housemate.wastesapi:
    container_name: housemate_wastesapi
    image: housemate.wastesapi
    build:
      context: .
      dockerfile: Housemate.Backend/Housemate.WastesApi/Dockerfile
    ports:
      - "8003:80"

  housemate.weatherapi:
    container_name: housemate_weatherapi
    image: housemate.weatherapi
    build:
      context: .
      dockerfile: Housemate.Backend/Housemate.WeatherApi/Dockerfile
    ports:
      - "8004:80"

  housemate.apigateway:
    container_name: housemate_apigateway
    image: housemate.apigateway
    build:
      context: .
      dockerfile: Housemate.ApiGateway/Dockerfile
    ports:
      - "8000:80"

  cache:
    container_name: house_rediscache
    image: redis:latest
    ports:
      - "6379:6379"