version: '3.4'
services:
  api-gateway:
    build:
      context: .
      dockerfile: Housemate.ApiGateway/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - identity-api
      - housing-task-api
      - wastes-api
      - weather-api

  identity-api:
    build:
      context: .
      dockerfile: Housemate.Backend/Housemate.IdentityApi/Dockerfile
    ports:
      - "5001:80"

  housing-task-api:
    build:
      context: .
      dockerfile: Housemate.Backend/Housemate.HousingTasksApi/Dockerfile
    ports:
      - "5002:80"

  wastes-api:
    build:
      context: .
      dockerfile: Housemate.Backend/Housemate.WastesApi/Dockerfile
    ports:
      - "5003:80"

  weather-api:
    build:
      context: .
      dockerfile: Housemate.Backend/Housemate.WeatherApi/Dockerfile
    ports:
      - "5004:80"
