// <auto-generated />
using System;
using Housemate.Application.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Housemate.Application.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230519161810_RenameCreationTaskName")]
    partial class RenameCreationTaskName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Housemate.Application.Models.HousingTasks.HousingTask", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("HousingTasks", (string)null);
                });

            modelBuilder.Entity("Housemate.Application.Models.StudentInfo.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("Birthdate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .IsDescending();

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("Housemate.Application.Models.Wastes.Waste", b =>
                {
                    b.Property<DateOnly>("CollectionDay")
                        .HasColumnType("date");

                    b.Property<int>("WasteType")
                        .HasColumnType("int");

                    b.HasKey("CollectionDay");

                    b.ToTable("Wastes", (string)null);
                });

            modelBuilder.Entity("Housemate.Application.Models.HousingTasks.HousingTask", b =>
                {
                    b.HasOne("Housemate.Application.Models.StudentInfo.Student", null)
                        .WithMany("HousingTasks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Housemate.Application.Models.StudentInfo.Student", b =>
                {
                    b.Navigation("HousingTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
